branch-defaults:
  master:
    environment: ShescodingProjects-env
environment-defaults:
  ShescodingProjects-env:
    branch: null
    repository: null
global:
  application_name: shescoding-projects
  default_ec2_keyname: aws-eb-shescoding-projects
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.5
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application

